export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES';
export const FETCH_REPOSITORY_ISSUES = 'FETCH_REPOSITORY_ISSUES';
export const FETCH_ISSUE = 'FETCH_ISSUE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const DELETE_SESSION = 'DELETE_SESSION';
